language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t nadimmahesaniya/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nadimmahesaniya/react-test npm test -- --coverage

after_success:
  - docker build -t nadimmahesaniya/multi-client ./client
  - docker build -t nadimmahesaniya/multi-nginx ./nginx
  - docker build -t nadimmahesaniya/multi-server ./server
  - docker build -t nadimmahesaniya/multi-worker ./worker
  #Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push nadimmahesaniya/multi-client
  - docker push nadimmahesaniya/multi-nginx
  - docker push nadimmahesaniya/multi-server
  - docker push nadimmahesaniya/multi-worker

